---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: OSL
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_solo
  data_bags_path: "test/integration/data_bags"
  encrypted_data_bag_secret_key_path: "encrypted_data_bag_secret"
  attributes:
    mysql:
      server_root_password: rootpass
      server_debian_password: debpass
      server_repl_password: replpass
    authorization:
      sudo:
        users:
          - vagrant
          - centos
    omnibus_updater:
      disabled: true

platforms:
- name: centos-6.5
  driver_plugin: openstack
  driver_config:
    username: centos
    image_ref: "CentOS 6.5"

suites:
  - name: default
    run_list:
     - recipe[yum]
     - recipe[git]
     - recipt[nginx]
     - recipe[pgd::default]
     - recipe[python::pip]
